insert into `song` (`title`, `artist`) values ("Don't Pan Me", "Alberta Hunter");
insert into `song` (`title`, `artist`) values ("Warm And Sunny Day", "Barrington Levy");
insert into `song` (`title`, `artist`) values ("Looking My Love", "Barrington Levy");
insert into `song` (`title`, `artist`) values ("Warm And Sunny Day", "Barrington Levy");
insert into `song` (`title`, `artist`) values ("Mandela You're Free", "Barrington Levy");
insert into `song` (`title`, `artist`) values ("Something In My Heart (Full Vocal)", "Barrington Levy");
insert into `song` (`title`, `artist`) values ("Airy Man Blues", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Wreck Of The Old 97", "Vernon Dalhart");
insert into `song` (`title`, `artist`) values ("The Prisoner's Song", "Vernon Dalhart");
insert into `song` (`title`, `artist`) values ("Wreck Of The Old 97", "Vernon Dalhart");
insert into `song` (`title`, `artist`) values ("The Prisoner's Song", "Vernon Dalhart");
insert into `song` (`title`, `artist`) values ("Careless Love Blues", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("Cast Away", "Clarence Williams' Blue Five");
insert into `song` (`title`, `artist`) values ("Pickin' On Your Baby", "Clarence Williams' Blue Five");
insert into `song` (`title`, `artist`) values ("Pickin' On Your Baby", "Clarence Williams' Blue Five");
insert into `song` (`title`, `artist`) values ("All I Want Is A Spoonful", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Maxwell Street Blues", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Shake That Thing", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Georgia Man", "Bertha 'Chippie' Hill");
insert into `song` (`title`, `artist`) values ("Trouble in Mind", "Bertha 'Chippie' Hill");
insert into `song` (`title`, `artist`) values ("Trouble In Mind", "Bertha Chippie Hill");
insert into `song` (`title`, `artist`) values ("The Gin House Blues", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("West Coast Blues", "Blind Blake");
insert into `song` (`title`, `artist`) values ("West Coast Blues", "Blind Blake");
insert into `song` (`title`, `artist`) values ("West Coast Blues", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Early Morning Blues", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Dry Southern Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Long Lonesome Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Long Lonesome Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Got The Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Beggin' Back", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Booster Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Black And Blue Bottom", "Joe Venuti_ Eddie Lang");
insert into `song` (`title`, `artist`) values ("I'm A Mighty Tight Woman", "Sippie Wallace");
insert into `song` (`title`, `artist`) values ("Bedroom Blues", "Sippie Wallace");
insert into `song` (`title`, `artist`) values ("Bedroom Blues", "Sippie Wallace");
insert into `song` (`title`, `artist`) values ("I'm a Mighty Tight Woman", "Sippie Wallace");
insert into `song` (`title`, `artist`) values ("Lock And Key", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("After You've Gone", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("Southern Rag", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Southern Rag", "Blind Blake");
insert into `song` (`title`, `artist`) values ("That Will Never Happen No More", "Blind Blake");
insert into `song` (`title`, `artist`) values ("He's In The Jailhouse Now", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Shuckin' Sugar Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Hot Dogs", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Booger Rooger Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("See That My Grave's Kept Clean", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Bad Luck Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Easy Rider Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Wartime Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Weary Dogs Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Struck Sorrow Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Bad Luck Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Bad Luck Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Booger Rooger Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Broke And Hungry", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Broke And Hungry", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Writing Paper Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Wake Nicodemus", "Frank Crumit");
insert into `song` (`title`, `artist`) values ("Singin' The Blues", "Frankie Trumbauer");
insert into `song` (`title`, `artist`) values ("Falling Down Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Big Chief Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Big Chief Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Big Chief Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Big Chief Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Stardust", "Hoagy Carmichael");
insert into `song` (`title`, `artist`) values ("Stardust", "Hoagy Carmichael");
insert into `song` (`title`, `artist`) values ("Stardust", "Hoagy Carmichael");
insert into `song` (`title`, `artist`) values ("One Night In Havana", "Hoagy Carmichael");
insert into `song` (`title`, `artist`) values ("Goin' Places", "Joe Venuti_ Eddie Lang");
insert into `song` (`title`, `artist`) values ("Doin' Things", "Joe Venuti_ Eddie Lang");
insert into `song` (`title`, `artist`) values ("Coffee Grindin' Blues", "Lucille Bogan");
insert into `song` (`title`, `artist`) values ("Pot Hound Blues", "Lucille Bogan");
insert into `song` (`title`, `artist`) values ("Ma Rainey's Black Bottom", "Ma Rainey");
insert into `song` (`title`, `artist`) values ("Ma Rainey's Black Bottom", "Ma Rainey");
insert into `song` (`title`, `artist`) values ("Fat Mouth Blues", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Skoodle-Um-Skoo", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Bright Eyes", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Blue Monday Morning Blues", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Look Out Papa Don't Tear Your Pants", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Me And My Gin", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("Big Bill Blues", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("See That My Grave Is Kept Clean", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Prison Cell Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("How Long How Long", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Prison Cell Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Mother's Children Have A Hard Time", "Blind Willie Johnson");
insert into `song` (`title`, `artist`) values ("It's Nobody's Fault But Mine", "Blind Willie Johnson");
insert into `song` (`title`, `artist`) values ("It's Nobody's Fault but Mine", "Blind Willie Johnson");
insert into `song` (`title`, `artist`) values ("It's Nobody's Fault But Mine", "Blind Willie Johnson");
insert into `song` (`title`, `artist`) values ("Mother's Children Have A Hard Time", "Blind Willie Johnson");
insert into `song` (`title`, `artist`) values ("If I Had My Way I'd Tear The Building Down", "Blind Willie Johnson");
insert into `song` (`title`, `artist`) values ("Mother's Children Have A Hard Time", "Blind Willie Johnson");
insert into `song` (`title`, `artist`) values ("It's Nobody's Fault But Mine", "Blind Willie Johnson");
insert into `song` (`title`, `artist`) values ("It's Nobody's Fault But Mine", "Blind Willie Johnson");
insert into `song` (`title`, `artist`) values ("Three Women Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Statesboro Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Dark Night Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Loving Talking Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Madison Street Rag", "Cannon's Jug Stompers");
insert into `song` (`title`, `artist`) values ("Minglewood Blues", "Cannon's Jug Stompers");
insert into `song` (`title`, `artist`) values ("State Street Jive", "Cow Cow Davenport");
insert into `song` (`title`, `artist`) values ("Cow Cow Blues", "Cow Cow Davenport");
insert into `song` (`title`, `artist`) values ("Cow Cow Blues", "Cow Cow Davenport");
insert into `song` (`title`, `artist`) values ("Cow Cow Blues", "Cow Cow Davenport");
insert into `song` (`title`, `artist`) values ("Cow Cow Blues", "Cow Cow Davenport");
insert into `song` (`title`, `artist`) values ("Jubilee Stomp", "Duke Ellington & His Orchestra");
insert into `song` (`title`, `artist`) values ("Hot And Bothered", "Duke Ellington & His Orchestra");
insert into `song` (`title`, `artist`) values ("The Mooche", "Duke Ellington & His Orchestra");
insert into `song` (`title`, `artist`) values ("Bedtime Blues", "Frank Stokes");
insert into `song` (`title`, `artist`) values ("Downtown Blues", "Frank Stokes");
insert into `song` (`title`, `artist`) values ("Downtown Blues", "Frank Stokes");
insert into `song` (`title`, `artist`) values ("Bedtime Blues", "Frank Stokes");
insert into `song` (`title`, `artist`) values ("Cannonball Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Everybody's Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Kassie Jones (Part 2)", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Kassie Jones (Part 1)", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Mean Old Bed Bug Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Good Looking Girl Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Judge Harsh Blues  (Alternate take)", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Rock Island Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Minglewood Blues", "Gus Cannon's Jug Stompers");
insert into `song` (`title`, `artist`) values ("Careless Love", "Lonnie Johnson");
insert into `song` (`title`, `artist`) values ("Blue Ghost Blues", "Lonnie Johnson");
insert into `song` (`title`, `artist`) values ("Way Down That Lonesome Road", "Lonnie Johnson");
insert into `song` (`title`, `artist`) values ("Life Saver Blues", "Lonnie Johnson");
insert into `song` (`title`, `artist`) values ("Hotter Than That", "Louis Armstrong");
insert into `song` (`title`, `artist`) values ("Evergreen Money Blues", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("Sugar Pudding", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("Nobody's Dirty Business", "Mississippi John Hurt");
insert into `song` (`title`, `artist`) values ("Ash Tray Blues", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Lindberg Hop", "The Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("I Have To Have You", "Annette Hanshaw");
insert into `song` (`title`, `artist`) values ("Don't Cry Baby", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("Nobody Knows You When You're Down And Out", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("Nobody Knows You When You're Down And Out", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("He's Got Me Goin'", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("Penitentiary", "Bessie Tucker");
insert into `song` (`title`, `artist`) values ("Old Black Mary", "Bessie Tucker");
insert into `song` (`title`, `artist`) values ("Bessie's Moan", "Bessie Tucker");
insert into `song` (`title`, `artist`) values ("Keep It Home", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Keep It Home", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Diddie Wa Diddie", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Keep It Home", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Sweet Jivin' Mama", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Pneumonia Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Pneumonia Blues", "Blind Lemon Jefferson");
insert into `song` (`title`, `artist`) values ("Drive Away Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Drive Away Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Love Changing Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Walk Right In", "Cannon's Jug Stompers");
insert into `song` (`title`, `artist`) values ("Walk Right In", "Cannon's Jug Stompers");
insert into `song` (`title`, `artist`) values ("Noah's Blues", "Cannon's Jug Stompers");
insert into `song` (`title`, `artist`) values ("Walk Right In", "Cannon's Jug Stompers");
insert into `song` (`title`, `artist`) values ("Ripley Blues", "Cannon's Jug Stompers");
insert into `song` (`title`, `artist`) values ("A Spoonful Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Tom Rushen Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Down The Dirt Road Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Pea Vine Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Screamin' And Hollerin' The Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Mississippi Boweavil Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Down The Dirt Road Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("A Spoonful Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Pony Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Pony Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Tom Rushen Blues", "Charlie Patton");
insert into `song` (`title`, `artist`) values ("Little Sadie", "Clarence Ashley");
insert into `song` (`title`, `artist`) values ("Ain't Misbehavin'", "Fats Waller");
insert into `song` (`title`, `artist`) values ("Ain't misbehavin'", "Fats Waller");
insert into `song` (`title`, `artist`) values ("Ain't Misbehavin'", "Fats Waller");
insert into `song` (`title`, `artist`) values ("Ain't Misbehavin'", "Fats Waller");
insert into `song` (`title`, `artist`) values ("I Got Mine", "Frank Stokes");
insert into `song` (`title`, `artist`) values ("How Long", "Frank Stokes");
insert into `song` (`title`, `artist`) values ("I Got Mine", "Frank Stokes");
insert into `song` (`title`, `artist`) values ("How Long", "Frank Stokes");
insert into `song` (`title`, `artist`) values ("Jive Man Blues", "Frankie 'Half Pint' Jaxon");
insert into `song` (`title`, `artist`) values ("Jive Man Blues", "Frankie 'Half-Pint' Jaxon");
insert into `song` (`title`, `artist`) values ("Ain't Misbehavin'", "Frédéric Meinders");
insert into `song` (`title`, `artist`) values ("Judge Harsh Blues", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Mistreatin' Mamma", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("I Will Turn Your Money Green", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("I Will Turn Your Money Green", "Furry Lewis");
insert into `song` (`title`, `artist`) values ("Roll and Tumble Blues", "Hambone Willie Newbern");
insert into `song` (`title`, `artist`) values ("Roll and Tumble Blues", "Hambone Willie Newbern");
insert into `song` (`title`, `artist`) values ("Pea Vine Blues", "Leadbelly & Friends");
insert into `song` (`title`, `artist`) values ("Low Land Moan", "Lonnie Johnson");
insert into `song` (`title`, `artist`) values ("Muddy Creek Blues", "Mary Johnson");
insert into `song` (`title`, `artist`) values ("Room Rent Blues", "Mary Johnson");
insert into `song` (`title`, `artist`) values ("Memphis Yo Yo Blues", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("Memphis Yo Yo Blues", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("On the Road Again", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("On The Road Again", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("On The Road Again", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("On The Road Again", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("K.C. Moan", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("On The Road Again", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("K.C. Moan", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("Just Because", "Nelstone´s Hawaiians");
insert into `song` (`title`, `artist`) values ("Jungle Man Blues", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Corn Liquor Blues", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Tailor Made Lover", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Baby Please Loan Me Your Heart", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("Pine Top's Boogie Woogie", "Pine Top Smith");
insert into `song` (`title`, `artist`) values ("Pine Top Blues", "Pine Top Smith");
insert into `song` (`title`, `artist`) values ("Pine Top's Boogie Woogie", "Pine Top Smith");
insert into `song` (`title`, `artist`) values ("Pine Top Blues", "Pine Top Smith");
insert into `song` (`title`, `artist`) values ("Pine Top's Boogie Woogie", "Pine Top Smith");
insert into `song` (`title`, `artist`) values ("That's No Way To Get Along", "Robert Wilkins");
insert into `song` (`title`, `artist`) values ("That's No Way To Get Along", "Robert Wilkins");
insert into `song` (`title`, `artist`) values ("That's No Way To Get Along", "Robert Wilkins");
insert into `song` (`title`, `artist`) values ("That's No Way To Get Along", "Robert Wilkins");
insert into `song` (`title`, `artist`) values ("Henry Ford Blues", "Roosevelt Sykes");
insert into `song` (`title`, `artist`) values ("Boot That Thing", "Roosevelt Sykes");
insert into `song` (`title`, `artist`) values ("Dying Mercy Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("On The Road Again", "The Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("K.C. Moan", "The Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("Big Fat Mama Blues", "Tommy Johnson");
insert into `song` (`title`, `artist`) values ("Canned Heat Blues", "Tommy Johnson");
insert into `song` (`title`, `artist`) values ("Canned Heat Blues", "Tommy Johnson");
insert into `song` (`title`, `artist`) values ("Big Fat Mama Blues", "Tommy Johnson");
insert into `song` (`title`, `artist`) values ("Canned heat blues", "Tommy Johnson");
insert into `song` (`title`, `artist`) values ("Canned Heat Blues", "Tommy Johnson");
insert into `song` (`title`, `artist`) values ("Canned Heat Blues", "Tommy Johnson");
insert into `song` (`title`, `artist`) values ("Canned Heat Blues", "Tommy Johnson");
insert into `song` (`title`, `artist`) values ("Canned Heat Blues", "Tommy Johnson");
insert into `song` (`title`, `artist`) values ("Skoodle Do Do", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("I Can't Be Satisfied", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("I Can't Be Satisfied", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("I Am In The Heavenly Way", "Bukka White");
insert into `song` (`title`, `artist`) values ("I Am in the Heavenly Way", "Bukka White");
insert into `song` (`title`, `artist`) values ("On the Sunny Side of the Street", "Casa Loma Orchestra");
insert into `song` (`title`, `artist`) values ("Exactly Like You", "Casa Loma Orchestra");
insert into `song` (`title`, `artist`) values ("Leave It That Way", "Casa Loma Orchestra");
insert into `song` (`title`, `artist`) values ("Anytime's the Time to Fall in Love", "Casa Loma Orchestra");
insert into `song` (`title`, `artist`) values ("Going To Move To Alabama", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Going To Move To Alabama", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Moon Going Down", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Moon Going Down", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Moon Going Down", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Moon Going Down", "Charley Patton");
insert into `song` (`title`, `artist`) values ("When Your Way Gets Dark", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Moon Going Down", "Charlie Patton");
insert into `song` (`title`, `artist`) values ("When Your Way Gets Dark", "Charlie Patton");
insert into `song` (`title`, `artist`) values ("Four Day Rider", "Leroy Carr");
insert into `song` (`title`, `artist`) values ("Kentucky Blues", "Little Hat Jones");
insert into `song` (`title`, `artist`) values ("Bye Bye Baby Blues", "Little Hat Jones");
insert into `song` (`title`, `artist`) values ("Rockin' Chair", "Louis Armstrong");
insert into `song` (`title`, `artist`) values ("Rockin' Chair", "Louis Armstrong & His Orchestra");
insert into `song` (`title`, `artist`) values ("Cocaine Habit Blues", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("Cocaine Habit Blues", "Memphis Jug Band");
insert into `song` (`title`, `artist`) values ("I'm Talking About You", "Memphis Minnie");
insert into `song` (`title`, `artist`) values ("Bumble Bee", "Memphis Minnie");
insert into `song` (`title`, `artist`) values ("Bumble Bee", "Memphis Minnie");
insert into `song` (`title`, `artist`) values ("Sitting On Top Of The World", "Mississippi Sheiks");
insert into `song` (`title`, `artist`) values ("Stop And Listen Blues", "Mississippi Sheiks");
insert into `song` (`title`, `artist`) values ("Sitting On Top Of The World", "Mississippi Sheiks");
insert into `song` (`title`, `artist`) values ("Sitting On Top Of The World", "Mississippi Sheiks");
insert into `song` (`title`, `artist`) values ("Sitting On Top Of The World", "Mississippi Sheiks");
insert into `song` (`title`, `artist`) values ("Street Car Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Milk Cow Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Street Car Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Milk Cow Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Bye Bye Baby Blues", "Special EFX");
insert into `song` (`title`, `artist`) values ("You Rascal You", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Bear Cat's Kitten", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Safety Mama", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("When I Take My Sugar To Tea", "Boswell Sisters");
insert into `song` (`title`, `artist`) values ("The New 'Frisco Train", "Bukka White");
insert into `song` (`title`, `artist`) values ("The Panama Limited", "Bukka White");
insert into `song` (`title`, `artist`) values ("The Panama Limited", "Bukka White");
insert into `song` (`title`, `artist`) values ("The New 'Frisco Train", "Bukka White");
insert into `song` (`title`, `artist`) values ("Dry Well Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Bird Nest Bound", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Bird Nest Bound", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Special Rider Blues", "Skip James");
insert into `song` (`title`, `artist`) values ("Cypress Grove Blues", "Skip James");
insert into `song` (`title`, `artist`) values ("Special Rider Blues", "Skip James");
insert into `song` (`title`, `artist`) values ("I'M So Glad", "Skip James");
insert into `song` (`title`, `artist`) values ("I'm So Glad", "Skip James");
insert into `song` (`title`, `artist`) values ("Devil Got My Woman", "Skip James");
insert into `song` (`title`, `artist`) values ("Devil Got My Woman", "Skip James");
insert into `song` (`title`, `artist`) values ("Devil Got My Woman", "Skip James");
insert into `song` (`title`, `artist`) values ("Cypress Grove Blues", "Skip James");
insert into `song` (`title`, `artist`) values ("Cypress Grove Blues", "Skip James");
insert into `song` (`title`, `artist`) values ("Devil Got My Woman", "Skip James");
insert into `song` (`title`, `artist`) values ("Cypress Grove Blues", "Skip James");
insert into `song` (`title`, `artist`) values ("I'm So Glad", "Skip James");
insert into `song` (`title`, `artist`) values ("Devil Got My Woman", "Skip James");
insert into `song` (`title`, `artist`) values ("Devil Got My Woman", "Skip James");
insert into `song` (`title`, `artist`) values ("Devil Got My Woman", "Skip James");
insert into `song` (`title`, `artist`) values ("Special Rider Blues", "Skip James");
insert into `song` (`title`, `artist`) values ("I'm So Glad", "Skip James");
insert into `song` (`title`, `artist`) values ("Special Rider Blues", "Skip James");
insert into `song` (`title`, `artist`) values ("Devil Got My Woman", "Skip James");
insert into `song` (`title`, `artist`) values ("Cypress Grove Blues", "Skip James");
insert into `song` (`title`, `artist`) values ("I'm So Glad", "Skip James");
insert into `song` (`title`, `artist`) values ("Devil Got My Woman", "Skip James");
insert into `song` (`title`, `artist`) values ("Bumble Bee Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Stop And Listen Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Georgia Hound Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Champagne Charlie Is My Name", "Blind Blake");
insert into `song` (`title`, `artist`) values ("Searching the Desert for the Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Searching The Desert For The Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("Rollin' Mama Blues", "Blind Willie McTell");
insert into `song` (`title`, `artist`) values ("It Don't Mean A Thing (If It Ain't Got That Swing)", "Duke Ellington & His Orchestra");
insert into `song` (`title`, `artist`) values ("Police Station Blues", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("All Alone Blues", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("Western Bound Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("You Can't Get That Stuff No More", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Turpentine Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Things 'Bout Coming My Way No. 2", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Take Me For A Buggy Ride", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("Stormy Weather", "Ethel Waters");
insert into `song` (`title`, `artist`) values ("Love Is the Thing", "Ethel Waters");
insert into `song` (`title`, `artist`) values ("Stormy Weather", "Ethel Waters");
insert into `song` (`title`, `artist`) values ("I'm Nuts About That Gal", "Lonnie Johnson");
insert into `song` (`title`, `artist`) values ("Where Is My Good Man", "Memphis Minnie");
insert into `song` (`title`, `artist`) values ("Long Tall Mama", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("Hard Headed Woman", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("Poor Me", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Love My Stuff", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Poor Me", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Jersey Bull Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Poor Me", "Charley Patton");
insert into `song` (`title`, `artist`) values ("Jersey Bull Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("34 Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("34 Blues", "Charley Patton");
insert into `song` (`title`, `artist`) values ("34 Blues", "Charlie Patton");
insert into `song` (`title`, `artist`) values ("Love My Stuff", "Charlie Patton");
insert into `song` (`title`, `artist`) values ("Don't Be That Way", "Chick Webb & His Orchestra");
insert into `song` (`title`, `artist`) values ("Don't Be That Way", "Chick Webb & His Orchestra");
insert into `song` (`title`, `artist`) values ("Blue Minor", "Chick Webb & His Orchestra");
insert into `song` (`title`, `artist`) values ("Solitude", "Duke Ellington & His Orchestra");
insert into `song` (`title`, `artist`) values ("Solitude", "Duke Ellington & His Orchestra");
insert into `song` (`title`, `artist`) values ("Blue Minor", "Ella Fitzgerald");
insert into `song` (`title`, `artist`) values ("Moonglow", "Ethel Waters");
insert into `song` (`title`, `artist`) values ("Easy Rider Blues", "Jimmie Davis");
insert into `song` (`title`, `artist`) values ("Milk Cow Blues", "Kokomo Arnold");
insert into `song` (`title`, `artist`) values ("Milk Cow Blues", "Kokomo Arnold");
insert into `song` (`title`, `artist`) values ("Old Original Kokomo Blues", "Kokomo Arnold");
insert into `song` (`title`, `artist`) values ("Milk Cow Blues", "Kokomo Arnold");
insert into `song` (`title`, `artist`) values ("Mean Mistreater Mama", "Leroy Carr");
insert into `song` (`title`, `artist`) values ("Black Angel Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("That Stuff Is Here", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Mean Mistreater Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("You Don't Want Me Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Keep Your Hands Off Her", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("49 Highway Blues", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Little Leg Woman", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Stepfather Blues", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Somebody's Been Borrowing That Stuff", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Wild Cow Blues", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Wild Cow Blues", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("49 Highway Blues", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Baby You Gotta Change Your Mind", "Blind Boy Fuller");
insert into `song` (`title`, `artist`) values ("Somebody's Been Playing With That Thing", "Blind Boy Fuller");
insert into `song` (`title`, `artist`) values ("Down Home Rag", "Chick Webb & His Orchestra");
insert into `song` (`title`, `artist`) values ("I'll Chase The Blues Away", "Chick Webb And His Orchestra");
insert into `song` (`title`, `artist`) values ("Rocks In My Bed", "Leroy Carr");
insert into `song` (`title`, `artist`) values ("Joe Louis Strut", "Memphis Minnie");
insert into `song` (`title`, `artist`) values ("If I Got What You Want", "Papa Charlie Jackson");
insert into `song` (`title`, `artist`) values ("All Night Long Blues", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("Down South Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Down South Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Drop Down Mama", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Stop That Thing", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Down South Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Drop Down Mama", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Stop That Thing", "Sleepy John Estes & John Henry Barbee");
insert into `song` (`title`, `artist`) values ("Stockyard Fire", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Good Liquor Gonna Carry Me Down", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("Worried Man blues", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Stack O' Dollars", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Summertime", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Billie's Blues", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Pennies From Heaven", "Bing Crosby");
insert into `song` (`title`, `artist`) values ("Pennies From Heaven", "Bing Crosby");
insert into `song` (`title`, `artist`) values ("Pennies From Heaven", "Bing Crosby");
insert into `song` (`title`, `artist`) values ("Babe You Got To Do Better", "Blind Boy Fuller");
insert into `song` (`title`, `artist`) values ("Truckin' My Blues Away", "Blind Boy Fuller");
insert into `song` (`title`, `artist`) values ("Truckin' My Blues Away", "Blind Boy Fuller");
insert into `song` (`title`, `artist`) values ("Echoes Of Harlem", "Duke Ellington & His Orchestra");
insert into `song` (`title`, `artist`) values ("Blue Lou", "Fletcher Henderson And His Orchestra");
insert into `song` (`title`, `artist`) values ("The Way You Look Tonight", "Fred Astaire");
insert into `song` (`title`, `artist`) values ("The way you look tonight", "Fred Astaire");
insert into `song` (`title`, `artist`) values ("Murder In The First Degree", "Lil Johnson");
insert into `song` (`title`, `artist`) values ("Scuffling Woman Blues", "Lil Johnson");
insert into `song` (`title`, `artist`) values ("We Were Dancing", "Noel Coward");
insert into `song` (`title`, `artist`) values ("Drinking Man Blues", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("Country Fool Blues", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("Old Shep", "Red Foley");
insert into `song` (`title`, `artist`) values ("Old Shep", "Red Foley");
insert into `song` (`title`, `artist`) values ("Old Shep", "Red Foley");
insert into `song` (`title`, `artist`) values ("Stormy Sea Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("I'm Gettin' Sentimental Over You", "Tommy Dorsey & His Orchestra");
insert into `song` (`title`, `artist`) values ("Brother James", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Rootin' Ground Hog", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("I Won't Be In Hard Luck No More", "Big Joe Williams");
insert into `song` (`title`, `artist`) values ("Without Your Love", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("I've Got My Love To Keep Me Warm", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Without Your Love", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Shake 'Em On Down", "Bukka White");
insert into `song` (`title`, `artist`) values ("Shake 'Em On Down", "Bukka White");
insert into `song` (`title`, `artist`) values ("Pinebluff Arkansas", "Bukka White");
insert into `song` (`title`, `artist`) values ("Parfum", "Django Reinhardt");
insert into `song` (`title`, `artist`) values ("Caravan", "Duke Ellington & His Famous Orchestra");
insert into `song` (`title`, `artist`) values ("Caravan", "Duke Ellington And His Orchestra");
insert into `song` (`title`, `artist`) values ("They Can't Take That Away From Me", "Fred Astaire");
insert into `song` (`title`, `artist`) values ("Things Are Looking Up", "Fred Astaire");
insert into `song` (`title`, `artist`) values ("Nice Work If You Can Get It", "Fred Astaire");
insert into `song` (`title`, `artist`) values ("Walking The Street", "Georgia White");
insert into `song` (`title`, `artist`) values ("You Don't Know My Mind", "Georgia White");
insert into `song` (`title`, `artist`) values ("Sugar Mama Blues", "John Lee Williamson");
insert into `song` (`title`, `artist`) values ("The Flying Crow", "King");
insert into `song` (`title`, `artist`) values ("Crazy With The Blues", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("Third Street's Going Down", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("Working On The Project", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("Night Time Is The Right Time", "Roosevelt Sykes");
insert into `song` (`title`, `artist`) values ("Night Time is the Right Time", "Roosevelt Sykes");
insert into `song` (`title`, `artist`) values ("Someday Baby Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Travel On", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Roll In My Sweet Baby's Arms", "The Monroe Brothers");
insert into `song` (`title`, `artist`) values ("Once In a While", "Tommy Dorsey & His Orchestra;The Four Esquires");
insert into `song` (`title`, `artist`) values ("Good time Tonight", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("Prelude To A Kiss", "Duke Ellington & His Orchestra");
insert into `song` (`title`, `artist`) values ("Swing Out Rhythm", "Lonnie Johnson");
insert into `song` (`title`, `artist`) values ("Swing Out Rhythm", "Lonnie Johnson");
insert into `song` (`title`, `artist`) values ("Got The Blues For The West End", "Lonnie Johnson");
insert into `song` (`title`, `artist`) values ("Shack Bully Stomp", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("Cake Alley", "Peetie Wheatstraw");
insert into `song` (`title`, `artist`) values ("Down On My Knees", "Roosevelt Sykes");
insert into `song` (`title`, `artist`) values ("Drunken Gambler", "Roosevelt Sykes");
insert into `song` (`title`, `artist`) values ("Down On My Knees", "Roosevelt Sykes");
insert into `song` (`title`, `artist`) values ("Special Agent (Railroad Police Blues)", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Easin' Back To Tennessee", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Liquor Store Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Clean Up At Home", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Liquor Store Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Liquor Store Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Easin' Back To Tennessee", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Special Agent (Railroad Police Blues)", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Seminole Blues", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Just A Dream", "Big Bill Broonzy");
insert into `song` (`title`, `artist`) values ("Fine and Mellow", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Strange Fruit", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Fine and Mellow", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Strange Fruit", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Strange Fruit", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Strange Fruit", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Fine and Mellow", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Strange Fruit", "Billie Holiday");
insert into `song` (`title`, `artist`) values ("Body And Soul", "Coleman Hawkins");
insert into `song` (`title`, `artist`) values ("Body And Soul", "Coleman Hawkins");
insert into `song` (`title`, `artist`) values ("Body And Soul", "Coleman Hawkins");
insert into `song` (`title`, `artist`) values ("Body and Soul", "Coleman Hawkins_ Kenny Clarke");
insert into `song` (`title`, `artist`) values ("Tuxedo Junction", "Erskine Hawkins & His Orchestra");
insert into `song` (`title`, `artist`) values ("Gin Mill Special", "Erskine Hawkins & His Orchestra");
insert into `song` (`title`, `artist`) values ("Tuxedo Junction", "Erskine Hawkins and His Orchestra");
insert into `song` (`title`, `artist`) values ("How Can You Face Me?", "Fats Waller");
insert into `song` (`title`, `artist`) values ("Don't You Leave Me Here", "Jelly Roll Morton's New Orleans Jazzmen");
insert into `song` (`title`, `artist`) values ("Don't You Leave Me Here", "Jelly Roll Morton's New Orleans Jazzmen");
insert into `song` (`title`, `artist`) values ("Ballin' the Jack", "Jelly Roll Morton's New Orleans Jazzmen");
insert into `song` (`title`, `artist`) values ("Jeepers Creepers", "Louis Armstrong");
insert into `song` (`title`, `artist`) values ("Jeepers creepers", "Louis Armstrong");
insert into `song` (`title`, `artist`) values ("Jeepers Creepers", "Louis Armstrong");
insert into `song` (`title`, `artist`) values ("Jeepers Creepers", "Louis Armstrong");
insert into `song` (`title`, `artist`) values ("Jeepers Creepers", "Louis Armstrong");
insert into `song` (`title`, `artist`) values ("Jeepers Creepers", "Louis Armstrong");
insert into `song` (`title`, `artist`) values ("Jeepers Creepers", "Louis Armstrong");
insert into `song` (`title`, `artist`) values ("Goin' Away Blues", "Pete Johnson & Big Joe Turner");
insert into `song` (`title`, `artist`) values ("This Train", "Sister Rosetta Tharpe");
insert into `song` (`title`, `artist`) values ("Fire Department Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Fire Department Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Everybody Oughta Make A Change", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Everybody Oughta Make a Change", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Fire Department Blues", "Sleepy John Estes");
insert into `song` (`title`, `artist`) values ("Blues For My Baby", "Tampa Red");
insert into `song` (`title`, `artist`) values ("Summit Ridge Drive", "Artie Shaw & His Gramercy Five");
insert into `song` (`title`, `artist`) values ("Summit Ridge Drive", "Artie Shaw and His Gramercy Five");
insert into `song` (`title`, `artist`) values ("Summit Ridge Drive", "Artie Shaw and His Gramercy Five");
insert into `song` (`title`, `artist`) values ("Young Woman's Blues", "Bessie Smith");
insert into `song` (`title`, `artist`) values ("Bye Bye Baby", "Blind Boy Fuller");
insert into `song` (`title`, `artist`) values ("You Got To Have Your Dollar", "Blind Boy Fuller");
insert into `song` (`title`, `artist`) values ("When Can I Change My Clothes", "Bukka White");
insert into `song` (`title`, `artist`) values ("Aberdeen Mississippi Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Good Gin Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Sleepy Man Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("When Can I Change My Clothes", "Bukka White");
insert into `song` (`title`, `artist`) values ("Good Gin Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("High Fever Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("High Fever Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Sleepy Man Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Parchman Farm Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Black Train Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Fixin' To Die Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Parchman Farm Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Fixin' To Die Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("District Attorney Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Strange Place Blues", "Bukka White");
insert into `song` (`title`, `artist`) values ("Aberdeen Mississippi Blues", "Bukka White");
